# Generated by Django 3.0.7 on 2020-06-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_quote_special_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='no_contact',
            field=models.BooleanField(default=False, help_text='If selected, we will notify you by text message once we have arrived at your property. We will then perform a walk around of your property to be able to provide a accurate quote. Once complete, we will follow up with a quote by email.', verbose_name='No Contact Quote'),
        ),
    ]
